import { Platform, PlatformLimits } from '../types/platform.types';

export const PLATFORM_LIMITS: Record<Platform, PlatformLimits> = {
  [Platform.TWITTER]: {
    platform: Platform.TWITTER,
    displayName: 'X (Twitter)',
    maxChars: 280,
    maxImages: 4,
    maxVideos: 1,
    maxVideoLengthSeconds: 140,
    maxImageSizeBytes: 5 * 1024 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
    supportedVideoFormats: ['video/mp4'],
    imageResizeWidth: 1000,
    supportsThreads: true,
    supportsCarousel: false,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: true,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#000000',
  },
  [Platform.LINKEDIN]: {
    platform: Platform.LINKEDIN,
    displayName: 'LinkedIn',
    maxChars: 3000,
    maxImages: 20,
    maxVideos: 1,
    maxImageSizeBytes: 10 * 1024 * 1024,
    maxVideoSizeBytes: 5 * 1024 * 1024 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif'],
    supportedVideoFormats: ['video/mp4'],
    imageResizeWidth: 1000,
    supportsThreads: false,
    supportsCarousel: true,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: true,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#0A66C2',
  },
  [Platform.LINKEDIN_PAGE]: {
    platform: Platform.LINKEDIN_PAGE,
    displayName: 'LinkedIn Page',
    maxChars: 3000,
    maxImages: 20,
    maxVideos: 1,
    maxImageSizeBytes: 10 * 1024 * 1024,
    maxVideoSizeBytes: 5 * 1024 * 1024 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif'],
    supportedVideoFormats: ['video/mp4'],
    imageResizeWidth: 1000,
    supportsThreads: false,
    supportsCarousel: true,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: true,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#0A66C2',
  },
  [Platform.FACEBOOK]: {
    platform: Platform.FACEBOOK,
    displayName: 'Facebook',
    maxChars: 63206,
    maxImages: 10,
    maxVideos: 1,
    maxImageSizeBytes: 4 * 1024 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: false,
    supportsCarousel: true,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#1877F2',
  },
  [Platform.INSTAGRAM]: {
    platform: Platform.INSTAGRAM,
    displayName: 'Instagram',
    maxChars: 2200,
    maxImages: 10,
    maxVideos: 1,
    maxImageSizeBytes: 8 * 1024 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4'],
    aspectRatios: { min: '4:5', max: '1.91:1' },
    supportsThreads: false,
    supportsCarousel: true,
    requiresTitle: false,
    requiresMedia: true,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#E4405F',
  },
  [Platform.YOUTUBE]: {
    platform: Platform.YOUTUBE,
    displayName: 'YouTube',
    maxChars: 5000,
    maxImages: 1,
    maxVideos: 1,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4', 'video/avi', 'video/mov'],
    supportsThreads: false,
    supportsCarousel: false,
    requiresTitle: true,
    requiresMedia: true,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#FF0000',
  },
  [Platform.TIKTOK]: {
    platform: Platform.TIKTOK,
    displayName: 'TikTok',
    maxChars: 2000,
    maxImages: 35,
    maxVideos: 1,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: false,
    supportsCarousel: false,
    requiresTitle: false,
    requiresMedia: true,
    requiresChannel: false,
    supportsComments: false,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#000000',
  },
  [Platform.REDDIT]: {
    platform: Platform.REDDIT,
    displayName: 'Reddit',
    maxChars: 10000,
    maxImages: 20,
    maxVideos: 1,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: false,
    supportsCarousel: false,
    requiresTitle: true,
    requiresMedia: false,
    requiresChannel: true,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: true,
    htmlSupport: false,
    iconColor: '#FF4500',
  },
  [Platform.PINTEREST]: {
    platform: Platform.PINTEREST,
    displayName: 'Pinterest',
    maxChars: 500,
    maxImages: 5,
    maxVideos: 1,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: false,
    supportsCarousel: true,
    requiresTitle: false,
    requiresMedia: true,
    requiresChannel: true,
    supportsComments: false,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#E60023',
  },
  [Platform.THREADS]: {
    platform: Platform.THREADS,
    displayName: 'Threads',
    maxChars: 500,
    maxImages: 10,
    maxVideos: 1,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: true,
    supportsCarousel: true,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#000000',
  },
  [Platform.DISCORD]: {
    platform: Platform.DISCORD,
    displayName: 'Discord',
    maxChars: 1980,
    maxImages: 10,
    maxVideos: 1,
    maxImageSizeBytes: 25 * 1024 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: false,
    supportsCarousel: false,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: true,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: true,
    htmlSupport: false,
    iconColor: '#5865F2',
  },
  [Platform.SLACK]: {
    platform: Platform.SLACK,
    displayName: 'Slack',
    maxChars: 400000,
    maxImages: 10,
    maxVideos: 0,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif'],
    supportedVideoFormats: [],
    supportsThreads: false,
    supportsCarousel: false,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: true,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: true,
    htmlSupport: false,
    iconColor: '#4A154B',
  },
  [Platform.MASTODON]: {
    platform: Platform.MASTODON,
    displayName: 'Mastodon',
    maxChars: 500,
    maxImages: 4,
    maxVideos: 1,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: true,
    supportsCarousel: false,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: true,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#6364FF',
  },
  [Platform.BLUESKY]: {
    platform: Platform.BLUESKY,
    displayName: 'Bluesky',
    maxChars: 300,
    maxImages: 4,
    maxVideos: 1,
    maxImageSizeBytes: 976 * 1024,
    supportedImageFormats: ['image/jpeg', 'image/png'],
    supportedVideoFormats: ['video/mp4'],
    supportsThreads: true,
    supportsCarousel: false,
    requiresTitle: false,
    requiresMedia: false,
    requiresChannel: false,
    supportsComments: true,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: false,
    iconColor: '#0085FF',
  },
  [Platform.DRIBBBLE]: {
    platform: Platform.DRIBBBLE,
    displayName: 'Dribbble',
    maxChars: 40000,
    maxImages: 1,
    maxVideos: 0,
    supportedImageFormats: ['image/jpeg', 'image/png', 'image/gif'],
    supportedVideoFormats: [],
    supportsThreads: false,
    supportsCarousel: false,
    requiresTitle: true,
    requiresMedia: true,
    requiresChannel: false,
    supportsComments: false,
    supportsPoll: false,
    markdownSupport: false,
    htmlSupport: true,
    iconColor: '#EA4C89',
  },
};

/** Get limits for a specific platform, with Twitter premium override */
export function getPlatformLimits(platform: Platform, isPremium?: boolean): PlatformLimits {
  const limits = { ...PLATFORM_LIMITS[platform] };
  if (platform === Platform.TWITTER && isPremium) {
    limits.maxChars = 4000;
  }
  return limits;
}
