services:
  postiz:
    image: postiz-ghost:latest
    container_name: postiz
    restart: always
    env_file:
      - .env
    ports:
      - "4007:5000"
    depends_on:
      - postiz-postgres
      - postiz-redis
      - temporal
    networks:
      - postiz-network
      - temporal-network
    volumes:
      - postiz-uploads:/uploads

  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-local-pwd
      POSTGRES_USER: postiz-local
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postiz-network

  postiz-redis:
    image: redis:7-alpine
    container_name: postiz-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - postiz-network

  temporal-elasticsearch:
    container_name: temporal-elasticsearch
    image: elasticsearch:7.17.27
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    networks:
      - temporal-network
    expose:
      - 9200
    volumes:
      - temporal-es-data:/usr/share/elasticsearch/data

  temporal-postgresql:
    container_name: temporal-postgresql
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    networks:
      - temporal-network
    expose:
      - 5432
    volumes:
      - temporal-pg-data:/var/lib/postgresql/data

  temporal:
    container_name: temporal
    ports:
      - "7233:7233"
    image: temporalio/auto-setup:1.28.1
    depends_on:
      - temporal-postgresql
      - temporal-elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=temporal-elasticsearch
      - ES_VERSION=v7
      - TEMPORAL_NAMESPACE=default
    networks:
      - temporal-network
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

networks:
  postiz-network:
    driver: bridge
  temporal-network:
    driver: bridge

volumes:
  postgres-volume:
  postiz-uploads:
  temporal-pg-data:
  temporal-es-data: