/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PublicRouteImport } from './app/_public'
import { Route as ExtensionRouteImport } from './app/_extension'
import { Route as AppRouteImport } from './app/_app'
import { Route as AdminRouteRouteImport } from './app/admin/route'
import { Route as AdminIndexRouteImport } from './app/admin/index'
import { Route as PublicIndexRouteImport } from './app/_public/index'
import { Route as AppSiteRouteImport } from './app/_app/_site'
import { Route as AppPreviewRouteImport } from './app/_app/_preview'
import { Route as ExtensionModalRouteRouteImport } from './app/_extension/modal/route'
import { Route as AppAuthRouteRouteImport } from './app/_app/auth/route'
import { Route as AdminLoginIndexRouteImport } from './app/admin/login/index'
import { Route as PublicTermsIndexRouteImport } from './app/_public/terms/index'
import { Route as PublicPrivacyIndexRouteImport } from './app/_public/privacy/index'
import { Route as PublicLeaderboardIndexRouteImport } from './app/_public/leaderboard/index'
import { Route as PublicDashboardIndexRouteImport } from './app/_public/dashboard/index'
import { Route as AppAuthIndexRouteImport } from './app/_app/auth/index'
import { Route as AppOauthAuthorizeRouteRouteImport } from './app/_app/oauth/authorize/route'
import { Route as AppIntegrationsSocialRouteRouteImport } from './app/_app/integrations/social/route'
import { Route as AppSiteAgentsRouteRouteImport } from './app/_app/_site/agents/route'
import { Route as AdminCreatorsNewIndexRouteImport } from './app/admin/creators/new/index'
import { Route as PublicCreatorsIdIndexRouteImport } from './app/_public/creators/$id/index'
import { Route as ProviderProviderAddIndexRouteImport } from './app/_provider/provider/add/index'
import { Route as ProviderProviderPIndexRouteImport } from './app/_provider/provider/$p/index'
import { Route as AppOauthAuthorizeIndexRouteImport } from './app/_app/oauth/authorize/index'
import { Route as AppAuthLoginIndexRouteImport } from './app/_app/auth/login/index'
import { Route as AppAuthLoginRequiredIndexRouteImport } from './app/_app/auth/login-required/index'
import { Route as AppAuthForgotIndexRouteImport } from './app/_app/auth/forgot/index'
import { Route as AppAuthActivateIndexRouteImport } from './app/_app/auth/activate/index'
import { Route as AppSiteThirdPartyIndexRouteImport } from './app/_app/_site/third-party/index'
import { Route as AppSiteSettingsIndexRouteImport } from './app/_app/_site/settings/index'
import { Route as AppSitePlugsIndexRouteImport } from './app/_app/_site/plugs/index'
import { Route as AppSiteMediaIndexRouteImport } from './app/_app/_site/media/index'
import { Route as AppSiteLaunchesIndexRouteImport } from './app/_app/_site/launches/index'
import { Route as AppSiteErrIndexRouteImport } from './app/_app/_site/err/index'
import { Route as AppSiteBillingIndexRouteImport } from './app/_app/_site/billing/index'
import { Route as AppSiteAnalyticsIndexRouteImport } from './app/_app/_site/analytics/index'
import { Route as AppSiteAgentsIndexRouteImport } from './app/_app/_site/agents/index'
import { Route as AppPreviewPIdRouteRouteImport } from './app/_app/_preview/p/$id/route'
import { Route as AdminCreatorsIdEditIndexRouteImport } from './app/admin/creators/$id/edit/index'
import { Route as PublicCreatorsIdPlatformIndexRouteImport } from './app/_public/creators/$id/$platform/index'
import { Route as ExtensionModalStylePlatformIndexRouteImport } from './app/_extension/modal/$style/$platform/index'
import { Route as AppIntegrationsSocialProviderIndexRouteImport } from './app/_app/integrations/social/$provider/index'
import { Route as AppAuthForgotTokenIndexRouteImport } from './app/_app/auth/forgot/$token/index'
import { Route as AppAuthActivateCodeIndexRouteImport } from './app/_app/auth/activate/$code/index'
import { Route as AppSiteBillingLifetimeIndexRouteImport } from './app/_app/_site/billing/lifetime/index'
import { Route as AppSiteAgentsIdIndexRouteImport } from './app/_app/_site/agents/$id/index'
import { Route as AppSiteAdminErrorsIndexRouteImport } from './app/_app/_site/admin/errors/index'
import { Route as AppPreviewPIdIndexRouteImport } from './app/_app/_preview/p/$id/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/_extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/_preview',
  getParentRoute: () => AppRoute,
} as any)
const ExtensionModalRouteRoute = ExtensionModalRouteRouteImport.update({
  id: '/modal',
  path: '/modal',
  getParentRoute: () => ExtensionRoute,
} as any)
const AppAuthRouteRoute = AppAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicTermsIndexRoute = PublicTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyIndexRoute = PublicPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLeaderboardIndexRoute = PublicLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDashboardIndexRoute = PublicDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PublicRoute,
} as any)
const AppAuthIndexRoute = AppAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppOauthAuthorizeRouteRoute = AppOauthAuthorizeRouteRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsSocialRouteRoute =
  AppIntegrationsSocialRouteRouteImport.update({
    id: '/integrations/social',
    path: '/integrations/social',
    getParentRoute: () => AppRoute,
  } as any)
const AppSiteAgentsRouteRoute = AppSiteAgentsRouteRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppSiteRoute,
} as any)
const AdminCreatorsNewIndexRoute = AdminCreatorsNewIndexRouteImport.update({
  id: '/creators/new/',
  path: '/creators/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicCreatorsIdIndexRoute = PublicCreatorsIdIndexRouteImport.update({
  id: '/creators/$id/',
  path: '/creators/$id/',
  getParentRoute: () => PublicRoute,
} as any)
const ProviderProviderAddIndexRoute =
  ProviderProviderAddIndexRouteImport.update({
    id: '/_provider/provider/add/',
    path: '/provider/add/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProviderProviderPIndexRoute = ProviderProviderPIndexRouteImport.update({
  id: '/_provider/provider/$p/',
  path: '/provider/$p/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOauthAuthorizeIndexRoute = AppOauthAuthorizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOauthAuthorizeRouteRoute,
} as any)
const AppAuthLoginIndexRoute = AppAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthLoginRequiredIndexRoute =
  AppAuthLoginRequiredIndexRouteImport.update({
    id: '/login-required/',
    path: '/login-required/',
    getParentRoute: () => AppAuthRouteRoute,
  } as any)
const AppAuthForgotIndexRoute = AppAuthForgotIndexRouteImport.update({
  id: '/forgot/',
  path: '/forgot/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthActivateIndexRoute = AppAuthActivateIndexRouteImport.update({
  id: '/activate/',
  path: '/activate/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppSiteThirdPartyIndexRoute = AppSiteThirdPartyIndexRouteImport.update({
  id: '/third-party/',
  path: '/third-party/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteSettingsIndexRoute = AppSiteSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSitePlugsIndexRoute = AppSitePlugsIndexRouteImport.update({
  id: '/plugs/',
  path: '/plugs/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteMediaIndexRoute = AppSiteMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteLaunchesIndexRoute = AppSiteLaunchesIndexRouteImport.update({
  id: '/launches/',
  path: '/launches/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteErrIndexRoute = AppSiteErrIndexRouteImport.update({
  id: '/err/',
  path: '/err/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteBillingIndexRoute = AppSiteBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteAnalyticsIndexRoute = AppSiteAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteAgentsIndexRoute = AppSiteAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSiteAgentsRouteRoute,
} as any)
const AppPreviewPIdRouteRoute = AppPreviewPIdRouteRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AdminCreatorsIdEditIndexRoute =
  AdminCreatorsIdEditIndexRouteImport.update({
    id: '/creators/$id/edit/',
    path: '/creators/$id/edit/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const PublicCreatorsIdPlatformIndexRoute =
  PublicCreatorsIdPlatformIndexRouteImport.update({
    id: '/creators/$id/$platform/',
    path: '/creators/$id/$platform/',
    getParentRoute: () => PublicRoute,
  } as any)
const ExtensionModalStylePlatformIndexRoute =
  ExtensionModalStylePlatformIndexRouteImport.update({
    id: '/$style/$platform/',
    path: '/$style/$platform/',
    getParentRoute: () => ExtensionModalRouteRoute,
  } as any)
const AppIntegrationsSocialProviderIndexRoute =
  AppIntegrationsSocialProviderIndexRouteImport.update({
    id: '/$provider/',
    path: '/$provider/',
    getParentRoute: () => AppIntegrationsSocialRouteRoute,
  } as any)
const AppAuthForgotTokenIndexRoute = AppAuthForgotTokenIndexRouteImport.update({
  id: '/forgot/$token/',
  path: '/forgot/$token/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthActivateCodeIndexRoute =
  AppAuthActivateCodeIndexRouteImport.update({
    id: '/activate/$code/',
    path: '/activate/$code/',
    getParentRoute: () => AppAuthRouteRoute,
  } as any)
const AppSiteBillingLifetimeIndexRoute =
  AppSiteBillingLifetimeIndexRouteImport.update({
    id: '/billing/lifetime/',
    path: '/billing/lifetime/',
    getParentRoute: () => AppSiteRoute,
  } as any)
const AppSiteAgentsIdIndexRoute = AppSiteAgentsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppSiteAgentsRouteRoute,
} as any)
const AppSiteAdminErrorsIndexRoute = AppSiteAdminErrorsIndexRouteImport.update({
  id: '/admin/errors/',
  path: '/admin/errors/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppPreviewPIdIndexRoute = AppPreviewPIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPreviewPIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/auth': typeof AppAuthRouteRouteWithChildren
  '/modal': typeof ExtensionModalRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/agents': typeof AppSiteAgentsRouteRouteWithChildren
  '/integrations/social': typeof AppIntegrationsSocialRouteRouteWithChildren
  '/oauth/authorize': typeof AppOauthAuthorizeRouteRouteWithChildren
  '/auth/': typeof AppAuthIndexRoute
  '/dashboard/': typeof PublicDashboardIndexRoute
  '/leaderboard/': typeof PublicLeaderboardIndexRoute
  '/privacy/': typeof PublicPrivacyIndexRoute
  '/terms/': typeof PublicTermsIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/p/$id': typeof AppPreviewPIdRouteRouteWithChildren
  '/agents/': typeof AppSiteAgentsIndexRoute
  '/analytics/': typeof AppSiteAnalyticsIndexRoute
  '/billing/': typeof AppSiteBillingIndexRoute
  '/err/': typeof AppSiteErrIndexRoute
  '/launches/': typeof AppSiteLaunchesIndexRoute
  '/media/': typeof AppSiteMediaIndexRoute
  '/plugs/': typeof AppSitePlugsIndexRoute
  '/settings/': typeof AppSiteSettingsIndexRoute
  '/third-party/': typeof AppSiteThirdPartyIndexRoute
  '/auth/activate/': typeof AppAuthActivateIndexRoute
  '/auth/forgot/': typeof AppAuthForgotIndexRoute
  '/auth/login-required/': typeof AppAuthLoginRequiredIndexRoute
  '/auth/login/': typeof AppAuthLoginIndexRoute
  '/oauth/authorize/': typeof AppOauthAuthorizeIndexRoute
  '/provider/$p/': typeof ProviderProviderPIndexRoute
  '/provider/add/': typeof ProviderProviderAddIndexRoute
  '/creators/$id/': typeof PublicCreatorsIdIndexRoute
  '/admin/creators/new/': typeof AdminCreatorsNewIndexRoute
  '/p/$id/': typeof AppPreviewPIdIndexRoute
  '/admin/errors/': typeof AppSiteAdminErrorsIndexRoute
  '/agents/$id/': typeof AppSiteAgentsIdIndexRoute
  '/billing/lifetime/': typeof AppSiteBillingLifetimeIndexRoute
  '/auth/activate/$code/': typeof AppAuthActivateCodeIndexRoute
  '/auth/forgot/$token/': typeof AppAuthForgotTokenIndexRoute
  '/integrations/social/$provider/': typeof AppIntegrationsSocialProviderIndexRoute
  '/modal/$style/$platform/': typeof ExtensionModalStylePlatformIndexRoute
  '/creators/$id/$platform/': typeof PublicCreatorsIdPlatformIndexRoute
  '/admin/creators/$id/edit/': typeof AdminCreatorsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/modal': typeof ExtensionModalRouteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/integrations/social': typeof AppIntegrationsSocialRouteRouteWithChildren
  '/auth': typeof AppAuthIndexRoute
  '/dashboard': typeof PublicDashboardIndexRoute
  '/leaderboard': typeof PublicLeaderboardIndexRoute
  '/privacy': typeof PublicPrivacyIndexRoute
  '/terms': typeof PublicTermsIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/agents': typeof AppSiteAgentsIndexRoute
  '/analytics': typeof AppSiteAnalyticsIndexRoute
  '/billing': typeof AppSiteBillingIndexRoute
  '/err': typeof AppSiteErrIndexRoute
  '/launches': typeof AppSiteLaunchesIndexRoute
  '/media': typeof AppSiteMediaIndexRoute
  '/plugs': typeof AppSitePlugsIndexRoute
  '/settings': typeof AppSiteSettingsIndexRoute
  '/third-party': typeof AppSiteThirdPartyIndexRoute
  '/auth/activate': typeof AppAuthActivateIndexRoute
  '/auth/forgot': typeof AppAuthForgotIndexRoute
  '/auth/login-required': typeof AppAuthLoginRequiredIndexRoute
  '/auth/login': typeof AppAuthLoginIndexRoute
  '/oauth/authorize': typeof AppOauthAuthorizeIndexRoute
  '/provider/$p': typeof ProviderProviderPIndexRoute
  '/provider/add': typeof ProviderProviderAddIndexRoute
  '/creators/$id': typeof PublicCreatorsIdIndexRoute
  '/admin/creators/new': typeof AdminCreatorsNewIndexRoute
  '/p/$id': typeof AppPreviewPIdIndexRoute
  '/admin/errors': typeof AppSiteAdminErrorsIndexRoute
  '/agents/$id': typeof AppSiteAgentsIdIndexRoute
  '/billing/lifetime': typeof AppSiteBillingLifetimeIndexRoute
  '/auth/activate/$code': typeof AppAuthActivateCodeIndexRoute
  '/auth/forgot/$token': typeof AppAuthForgotTokenIndexRoute
  '/integrations/social/$provider': typeof AppIntegrationsSocialProviderIndexRoute
  '/modal/$style/$platform': typeof ExtensionModalStylePlatformIndexRoute
  '/creators/$id/$platform': typeof PublicCreatorsIdPlatformIndexRoute
  '/admin/creators/$id/edit': typeof AdminCreatorsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_extension': typeof ExtensionRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/auth': typeof AppAuthRouteRouteWithChildren
  '/_extension/modal': typeof ExtensionModalRouteRouteWithChildren
  '/_app/_preview': typeof AppPreviewRouteWithChildren
  '/_app/_site': typeof AppSiteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/_site/agents': typeof AppSiteAgentsRouteRouteWithChildren
  '/_app/integrations/social': typeof AppIntegrationsSocialRouteRouteWithChildren
  '/_app/oauth/authorize': typeof AppOauthAuthorizeRouteRouteWithChildren
  '/_app/auth/': typeof AppAuthIndexRoute
  '/_public/dashboard/': typeof PublicDashboardIndexRoute
  '/_public/leaderboard/': typeof PublicLeaderboardIndexRoute
  '/_public/privacy/': typeof PublicPrivacyIndexRoute
  '/_public/terms/': typeof PublicTermsIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/_app/_preview/p/$id': typeof AppPreviewPIdRouteRouteWithChildren
  '/_app/_site/agents/': typeof AppSiteAgentsIndexRoute
  '/_app/_site/analytics/': typeof AppSiteAnalyticsIndexRoute
  '/_app/_site/billing/': typeof AppSiteBillingIndexRoute
  '/_app/_site/err/': typeof AppSiteErrIndexRoute
  '/_app/_site/launches/': typeof AppSiteLaunchesIndexRoute
  '/_app/_site/media/': typeof AppSiteMediaIndexRoute
  '/_app/_site/plugs/': typeof AppSitePlugsIndexRoute
  '/_app/_site/settings/': typeof AppSiteSettingsIndexRoute
  '/_app/_site/third-party/': typeof AppSiteThirdPartyIndexRoute
  '/_app/auth/activate/': typeof AppAuthActivateIndexRoute
  '/_app/auth/forgot/': typeof AppAuthForgotIndexRoute
  '/_app/auth/login-required/': typeof AppAuthLoginRequiredIndexRoute
  '/_app/auth/login/': typeof AppAuthLoginIndexRoute
  '/_app/oauth/authorize/': typeof AppOauthAuthorizeIndexRoute
  '/_provider/provider/$p/': typeof ProviderProviderPIndexRoute
  '/_provider/provider/add/': typeof ProviderProviderAddIndexRoute
  '/_public/creators/$id/': typeof PublicCreatorsIdIndexRoute
  '/admin/creators/new/': typeof AdminCreatorsNewIndexRoute
  '/_app/_preview/p/$id/': typeof AppPreviewPIdIndexRoute
  '/_app/_site/admin/errors/': typeof AppSiteAdminErrorsIndexRoute
  '/_app/_site/agents/$id/': typeof AppSiteAgentsIdIndexRoute
  '/_app/_site/billing/lifetime/': typeof AppSiteBillingLifetimeIndexRoute
  '/_app/auth/activate/$code/': typeof AppAuthActivateCodeIndexRoute
  '/_app/auth/forgot/$token/': typeof AppAuthForgotTokenIndexRoute
  '/_app/integrations/social/$provider/': typeof AppIntegrationsSocialProviderIndexRoute
  '/_extension/modal/$style/$platform/': typeof ExtensionModalStylePlatformIndexRoute
  '/_public/creators/$id/$platform/': typeof PublicCreatorsIdPlatformIndexRoute
  '/admin/creators/$id/edit/': typeof AdminCreatorsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/auth'
    | '/modal'
    | '/admin/'
    | '/agents'
    | '/integrations/social'
    | '/oauth/authorize'
    | '/auth/'
    | '/dashboard/'
    | '/leaderboard/'
    | '/privacy/'
    | '/terms/'
    | '/admin/login/'
    | '/p/$id'
    | '/agents/'
    | '/analytics/'
    | '/billing/'
    | '/err/'
    | '/launches/'
    | '/media/'
    | '/plugs/'
    | '/settings/'
    | '/third-party/'
    | '/auth/activate/'
    | '/auth/forgot/'
    | '/auth/login-required/'
    | '/auth/login/'
    | '/oauth/authorize/'
    | '/provider/$p/'
    | '/provider/add/'
    | '/creators/$id/'
    | '/admin/creators/new/'
    | '/p/$id/'
    | '/admin/errors/'
    | '/agents/$id/'
    | '/billing/lifetime/'
    | '/auth/activate/$code/'
    | '/auth/forgot/$token/'
    | '/integrations/social/$provider/'
    | '/modal/$style/$platform/'
    | '/creators/$id/$platform/'
    | '/admin/creators/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modal'
    | '/admin'
    | '/integrations/social'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/err'
    | '/launches'
    | '/media'
    | '/plugs'
    | '/settings'
    | '/third-party'
    | '/auth/activate'
    | '/auth/forgot'
    | '/auth/login-required'
    | '/auth/login'
    | '/oauth/authorize'
    | '/provider/$p'
    | '/provider/add'
    | '/creators/$id'
    | '/admin/creators/new'
    | '/p/$id'
    | '/admin/errors'
    | '/agents/$id'
    | '/billing/lifetime'
    | '/auth/activate/$code'
    | '/auth/forgot/$token'
    | '/integrations/social/$provider'
    | '/modal/$style/$platform'
    | '/creators/$id/$platform'
    | '/admin/creators/$id/edit'
  id:
    | '__root__'
    | '/admin'
    | '/_app'
    | '/_extension'
    | '/_public'
    | '/_app/auth'
    | '/_extension/modal'
    | '/_app/_preview'
    | '/_app/_site'
    | '/_public/'
    | '/admin/'
    | '/_app/_site/agents'
    | '/_app/integrations/social'
    | '/_app/oauth/authorize'
    | '/_app/auth/'
    | '/_public/dashboard/'
    | '/_public/leaderboard/'
    | '/_public/privacy/'
    | '/_public/terms/'
    | '/admin/login/'
    | '/_app/_preview/p/$id'
    | '/_app/_site/agents/'
    | '/_app/_site/analytics/'
    | '/_app/_site/billing/'
    | '/_app/_site/err/'
    | '/_app/_site/launches/'
    | '/_app/_site/media/'
    | '/_app/_site/plugs/'
    | '/_app/_site/settings/'
    | '/_app/_site/third-party/'
    | '/_app/auth/activate/'
    | '/_app/auth/forgot/'
    | '/_app/auth/login-required/'
    | '/_app/auth/login/'
    | '/_app/oauth/authorize/'
    | '/_provider/provider/$p/'
    | '/_provider/provider/add/'
    | '/_public/creators/$id/'
    | '/admin/creators/new/'
    | '/_app/_preview/p/$id/'
    | '/_app/_site/admin/errors/'
    | '/_app/_site/agents/$id/'
    | '/_app/_site/billing/lifetime/'
    | '/_app/auth/activate/$code/'
    | '/_app/auth/forgot/$token/'
    | '/_app/integrations/social/$provider/'
    | '/_extension/modal/$style/$platform/'
    | '/_public/creators/$id/$platform/'
    | '/admin/creators/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ExtensionRoute: typeof ExtensionRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ProviderProviderPIndexRoute: typeof ProviderProviderPIndexRoute
  ProviderProviderAddIndexRoute: typeof ProviderProviderAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_extension': {
      id: '/_extension'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/_site': {
      id: '/_app/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_preview': {
      id: '/_app/_preview'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_extension/modal': {
      id: '/_extension/modal'
      path: '/modal'
      fullPath: '/modal'
      preLoaderRoute: typeof ExtensionModalRouteRouteImport
      parentRoute: typeof ExtensionRoute
    }
    '/_app/auth': {
      id: '/_app/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AppAuthRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/terms/': {
      id: '/_public/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof PublicTermsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy/': {
      id: '/_public/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PublicPrivacyIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/leaderboard/': {
      id: '/_public/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof PublicLeaderboardIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dashboard/': {
      id: '/_public/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof PublicDashboardIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/auth/': {
      id: '/_app/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AppAuthIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/oauth/authorize': {
      id: '/_app/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof AppOauthAuthorizeRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/social': {
      id: '/_app/integrations/social'
      path: '/integrations/social'
      fullPath: '/integrations/social'
      preLoaderRoute: typeof AppIntegrationsSocialRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_site/agents': {
      id: '/_app/_site/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppSiteAgentsRouteRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/admin/creators/new/': {
      id: '/admin/creators/new/'
      path: '/creators/new'
      fullPath: '/admin/creators/new/'
      preLoaderRoute: typeof AdminCreatorsNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/creators/$id/': {
      id: '/_public/creators/$id/'
      path: '/creators/$id'
      fullPath: '/creators/$id/'
      preLoaderRoute: typeof PublicCreatorsIdIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_provider/provider/add/': {
      id: '/_provider/provider/add/'
      path: '/provider/add'
      fullPath: '/provider/add/'
      preLoaderRoute: typeof ProviderProviderAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_provider/provider/$p/': {
      id: '/_provider/provider/$p/'
      path: '/provider/$p'
      fullPath: '/provider/$p/'
      preLoaderRoute: typeof ProviderProviderPIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/oauth/authorize/': {
      id: '/_app/oauth/authorize/'
      path: '/'
      fullPath: '/oauth/authorize/'
      preLoaderRoute: typeof AppOauthAuthorizeIndexRouteImport
      parentRoute: typeof AppOauthAuthorizeRouteRoute
    }
    '/_app/auth/login/': {
      id: '/_app/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AppAuthLoginIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/auth/login-required/': {
      id: '/_app/auth/login-required/'
      path: '/login-required'
      fullPath: '/auth/login-required/'
      preLoaderRoute: typeof AppAuthLoginRequiredIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/auth/forgot/': {
      id: '/_app/auth/forgot/'
      path: '/forgot'
      fullPath: '/auth/forgot/'
      preLoaderRoute: typeof AppAuthForgotIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/auth/activate/': {
      id: '/_app/auth/activate/'
      path: '/activate'
      fullPath: '/auth/activate/'
      preLoaderRoute: typeof AppAuthActivateIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_site/third-party/': {
      id: '/_app/_site/third-party/'
      path: '/third-party'
      fullPath: '/third-party/'
      preLoaderRoute: typeof AppSiteThirdPartyIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/settings/': {
      id: '/_app/_site/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSiteSettingsIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/plugs/': {
      id: '/_app/_site/plugs/'
      path: '/plugs'
      fullPath: '/plugs/'
      preLoaderRoute: typeof AppSitePlugsIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/media/': {
      id: '/_app/_site/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AppSiteMediaIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/launches/': {
      id: '/_app/_site/launches/'
      path: '/launches'
      fullPath: '/launches/'
      preLoaderRoute: typeof AppSiteLaunchesIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/err/': {
      id: '/_app/_site/err/'
      path: '/err'
      fullPath: '/err/'
      preLoaderRoute: typeof AppSiteErrIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/billing/': {
      id: '/_app/_site/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppSiteBillingIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/analytics/': {
      id: '/_app/_site/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppSiteAnalyticsIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/agents/': {
      id: '/_app/_site/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppSiteAgentsIndexRouteImport
      parentRoute: typeof AppSiteAgentsRouteRoute
    }
    '/_app/_preview/p/$id': {
      id: '/_app/_preview/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AppPreviewPIdRouteRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/admin/creators/$id/edit/': {
      id: '/admin/creators/$id/edit/'
      path: '/creators/$id/edit'
      fullPath: '/admin/creators/$id/edit/'
      preLoaderRoute: typeof AdminCreatorsIdEditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/creators/$id/$platform/': {
      id: '/_public/creators/$id/$platform/'
      path: '/creators/$id/$platform'
      fullPath: '/creators/$id/$platform/'
      preLoaderRoute: typeof PublicCreatorsIdPlatformIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_extension/modal/$style/$platform/': {
      id: '/_extension/modal/$style/$platform/'
      path: '/$style/$platform'
      fullPath: '/modal/$style/$platform/'
      preLoaderRoute: typeof ExtensionModalStylePlatformIndexRouteImport
      parentRoute: typeof ExtensionModalRouteRoute
    }
    '/_app/integrations/social/$provider/': {
      id: '/_app/integrations/social/$provider/'
      path: '/$provider'
      fullPath: '/integrations/social/$provider/'
      preLoaderRoute: typeof AppIntegrationsSocialProviderIndexRouteImport
      parentRoute: typeof AppIntegrationsSocialRouteRoute
    }
    '/_app/auth/forgot/$token/': {
      id: '/_app/auth/forgot/$token/'
      path: '/forgot/$token'
      fullPath: '/auth/forgot/$token/'
      preLoaderRoute: typeof AppAuthForgotTokenIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/auth/activate/$code/': {
      id: '/_app/auth/activate/$code/'
      path: '/activate/$code'
      fullPath: '/auth/activate/$code/'
      preLoaderRoute: typeof AppAuthActivateCodeIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/_app/_site/billing/lifetime/': {
      id: '/_app/_site/billing/lifetime/'
      path: '/billing/lifetime'
      fullPath: '/billing/lifetime/'
      preLoaderRoute: typeof AppSiteBillingLifetimeIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_site/agents/$id/': {
      id: '/_app/_site/agents/$id/'
      path: '/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AppSiteAgentsIdIndexRouteImport
      parentRoute: typeof AppSiteAgentsRouteRoute
    }
    '/_app/_site/admin/errors/': {
      id: '/_app/_site/admin/errors/'
      path: '/admin/errors'
      fullPath: '/admin/errors/'
      preLoaderRoute: typeof AppSiteAdminErrorsIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/_app/_preview/p/$id/': {
      id: '/_app/_preview/p/$id/'
      path: '/'
      fullPath: '/p/$id/'
      preLoaderRoute: typeof AppPreviewPIdIndexRouteImport
      parentRoute: typeof AppPreviewPIdRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
  AdminCreatorsNewIndexRoute: typeof AdminCreatorsNewIndexRoute
  AdminCreatorsIdEditIndexRoute: typeof AdminCreatorsIdEditIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
  AdminCreatorsNewIndexRoute: AdminCreatorsNewIndexRoute,
  AdminCreatorsIdEditIndexRoute: AdminCreatorsIdEditIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppAuthRouteRouteChildren {
  AppAuthIndexRoute: typeof AppAuthIndexRoute
  AppAuthActivateIndexRoute: typeof AppAuthActivateIndexRoute
  AppAuthForgotIndexRoute: typeof AppAuthForgotIndexRoute
  AppAuthLoginRequiredIndexRoute: typeof AppAuthLoginRequiredIndexRoute
  AppAuthLoginIndexRoute: typeof AppAuthLoginIndexRoute
  AppAuthActivateCodeIndexRoute: typeof AppAuthActivateCodeIndexRoute
  AppAuthForgotTokenIndexRoute: typeof AppAuthForgotTokenIndexRoute
}

const AppAuthRouteRouteChildren: AppAuthRouteRouteChildren = {
  AppAuthIndexRoute: AppAuthIndexRoute,
  AppAuthActivateIndexRoute: AppAuthActivateIndexRoute,
  AppAuthForgotIndexRoute: AppAuthForgotIndexRoute,
  AppAuthLoginRequiredIndexRoute: AppAuthLoginRequiredIndexRoute,
  AppAuthLoginIndexRoute: AppAuthLoginIndexRoute,
  AppAuthActivateCodeIndexRoute: AppAuthActivateCodeIndexRoute,
  AppAuthForgotTokenIndexRoute: AppAuthForgotTokenIndexRoute,
}

const AppAuthRouteRouteWithChildren = AppAuthRouteRoute._addFileChildren(
  AppAuthRouteRouteChildren,
)

interface AppPreviewPIdRouteRouteChildren {
  AppPreviewPIdIndexRoute: typeof AppPreviewPIdIndexRoute
}

const AppPreviewPIdRouteRouteChildren: AppPreviewPIdRouteRouteChildren = {
  AppPreviewPIdIndexRoute: AppPreviewPIdIndexRoute,
}

const AppPreviewPIdRouteRouteWithChildren =
  AppPreviewPIdRouteRoute._addFileChildren(AppPreviewPIdRouteRouteChildren)

interface AppPreviewRouteChildren {
  AppPreviewPIdRouteRoute: typeof AppPreviewPIdRouteRouteWithChildren
}

const AppPreviewRouteChildren: AppPreviewRouteChildren = {
  AppPreviewPIdRouteRoute: AppPreviewPIdRouteRouteWithChildren,
}

const AppPreviewRouteWithChildren = AppPreviewRoute._addFileChildren(
  AppPreviewRouteChildren,
)

interface AppSiteAgentsRouteRouteChildren {
  AppSiteAgentsIndexRoute: typeof AppSiteAgentsIndexRoute
  AppSiteAgentsIdIndexRoute: typeof AppSiteAgentsIdIndexRoute
}

const AppSiteAgentsRouteRouteChildren: AppSiteAgentsRouteRouteChildren = {
  AppSiteAgentsIndexRoute: AppSiteAgentsIndexRoute,
  AppSiteAgentsIdIndexRoute: AppSiteAgentsIdIndexRoute,
}

const AppSiteAgentsRouteRouteWithChildren =
  AppSiteAgentsRouteRoute._addFileChildren(AppSiteAgentsRouteRouteChildren)

interface AppSiteRouteChildren {
  AppSiteAgentsRouteRoute: typeof AppSiteAgentsRouteRouteWithChildren
  AppSiteAnalyticsIndexRoute: typeof AppSiteAnalyticsIndexRoute
  AppSiteBillingIndexRoute: typeof AppSiteBillingIndexRoute
  AppSiteErrIndexRoute: typeof AppSiteErrIndexRoute
  AppSiteLaunchesIndexRoute: typeof AppSiteLaunchesIndexRoute
  AppSiteMediaIndexRoute: typeof AppSiteMediaIndexRoute
  AppSitePlugsIndexRoute: typeof AppSitePlugsIndexRoute
  AppSiteSettingsIndexRoute: typeof AppSiteSettingsIndexRoute
  AppSiteThirdPartyIndexRoute: typeof AppSiteThirdPartyIndexRoute
  AppSiteAdminErrorsIndexRoute: typeof AppSiteAdminErrorsIndexRoute
  AppSiteBillingLifetimeIndexRoute: typeof AppSiteBillingLifetimeIndexRoute
}

const AppSiteRouteChildren: AppSiteRouteChildren = {
  AppSiteAgentsRouteRoute: AppSiteAgentsRouteRouteWithChildren,
  AppSiteAnalyticsIndexRoute: AppSiteAnalyticsIndexRoute,
  AppSiteBillingIndexRoute: AppSiteBillingIndexRoute,
  AppSiteErrIndexRoute: AppSiteErrIndexRoute,
  AppSiteLaunchesIndexRoute: AppSiteLaunchesIndexRoute,
  AppSiteMediaIndexRoute: AppSiteMediaIndexRoute,
  AppSitePlugsIndexRoute: AppSitePlugsIndexRoute,
  AppSiteSettingsIndexRoute: AppSiteSettingsIndexRoute,
  AppSiteThirdPartyIndexRoute: AppSiteThirdPartyIndexRoute,
  AppSiteAdminErrorsIndexRoute: AppSiteAdminErrorsIndexRoute,
  AppSiteBillingLifetimeIndexRoute: AppSiteBillingLifetimeIndexRoute,
}

const AppSiteRouteWithChildren =
  AppSiteRoute._addFileChildren(AppSiteRouteChildren)

interface AppIntegrationsSocialRouteRouteChildren {
  AppIntegrationsSocialProviderIndexRoute: typeof AppIntegrationsSocialProviderIndexRoute
}

const AppIntegrationsSocialRouteRouteChildren: AppIntegrationsSocialRouteRouteChildren =
  {
    AppIntegrationsSocialProviderIndexRoute:
      AppIntegrationsSocialProviderIndexRoute,
  }

const AppIntegrationsSocialRouteRouteWithChildren =
  AppIntegrationsSocialRouteRoute._addFileChildren(
    AppIntegrationsSocialRouteRouteChildren,
  )

interface AppOauthAuthorizeRouteRouteChildren {
  AppOauthAuthorizeIndexRoute: typeof AppOauthAuthorizeIndexRoute
}

const AppOauthAuthorizeRouteRouteChildren: AppOauthAuthorizeRouteRouteChildren =
  {
    AppOauthAuthorizeIndexRoute: AppOauthAuthorizeIndexRoute,
  }

const AppOauthAuthorizeRouteRouteWithChildren =
  AppOauthAuthorizeRouteRoute._addFileChildren(
    AppOauthAuthorizeRouteRouteChildren,
  )

interface AppRouteChildren {
  AppAuthRouteRoute: typeof AppAuthRouteRouteWithChildren
  AppPreviewRoute: typeof AppPreviewRouteWithChildren
  AppSiteRoute: typeof AppSiteRouteWithChildren
  AppIntegrationsSocialRouteRoute: typeof AppIntegrationsSocialRouteRouteWithChildren
  AppOauthAuthorizeRouteRoute: typeof AppOauthAuthorizeRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRouteRoute: AppAuthRouteRouteWithChildren,
  AppPreviewRoute: AppPreviewRouteWithChildren,
  AppSiteRoute: AppSiteRouteWithChildren,
  AppIntegrationsSocialRouteRoute: AppIntegrationsSocialRouteRouteWithChildren,
  AppOauthAuthorizeRouteRoute: AppOauthAuthorizeRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExtensionModalRouteRouteChildren {
  ExtensionModalStylePlatformIndexRoute: typeof ExtensionModalStylePlatformIndexRoute
}

const ExtensionModalRouteRouteChildren: ExtensionModalRouteRouteChildren = {
  ExtensionModalStylePlatformIndexRoute: ExtensionModalStylePlatformIndexRoute,
}

const ExtensionModalRouteRouteWithChildren =
  ExtensionModalRouteRoute._addFileChildren(ExtensionModalRouteRouteChildren)

interface ExtensionRouteChildren {
  ExtensionModalRouteRoute: typeof ExtensionModalRouteRouteWithChildren
}

const ExtensionRouteChildren: ExtensionRouteChildren = {
  ExtensionModalRouteRoute: ExtensionModalRouteRouteWithChildren,
}

const ExtensionRouteWithChildren = ExtensionRoute._addFileChildren(
  ExtensionRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDashboardIndexRoute: typeof PublicDashboardIndexRoute
  PublicLeaderboardIndexRoute: typeof PublicLeaderboardIndexRoute
  PublicPrivacyIndexRoute: typeof PublicPrivacyIndexRoute
  PublicTermsIndexRoute: typeof PublicTermsIndexRoute
  PublicCreatorsIdIndexRoute: typeof PublicCreatorsIdIndexRoute
  PublicCreatorsIdPlatformIndexRoute: typeof PublicCreatorsIdPlatformIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicDashboardIndexRoute: PublicDashboardIndexRoute,
  PublicLeaderboardIndexRoute: PublicLeaderboardIndexRoute,
  PublicPrivacyIndexRoute: PublicPrivacyIndexRoute,
  PublicTermsIndexRoute: PublicTermsIndexRoute,
  PublicCreatorsIdIndexRoute: PublicCreatorsIdIndexRoute,
  PublicCreatorsIdPlatformIndexRoute: PublicCreatorsIdPlatformIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ExtensionRoute: ExtensionRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ProviderProviderPIndexRoute: ProviderProviderPIndexRoute,
  ProviderProviderAddIndexRoute: ProviderProviderAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
