import { Prisma } from '@prisma/client';
import { PrismaRepository } from '@gitroom/nestjs-libraries/database/prisma/prisma.service';
import { CreateReligareProfileDto, UpdateReligareProfileDto } from '@gitroom/nestjs-libraries/dtos/religare/profile.dto';
export declare class ReligareRepository {
    private _profile;
    private _org;
    constructor(_profile: PrismaRepository<'religareProfile'>, _org: PrismaRepository<'organization'>);
    getContext(orgId: string): Prisma.Prisma__OrganizationClient<{
        religareContext: string;
    }, null, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    setContext(orgId: string, context: string): Prisma.Prisma__OrganizationClient<{
        religareContext: string;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    listProfiles(orgId: string, search?: string, page?: number): Prisma.PrismaPromise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        expertId: string;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
    }[]>;
    countProfiles(orgId: string): Prisma.PrismaPromise<number>;
    getProfileById(orgId: string, id: string): Prisma.Prisma__ReligareProfileClient<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }, null, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    getProfileByExpert(orgId: string, expertId: string): Prisma.Prisma__ReligareProfileClient<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }, null, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    createProfile(orgId: string, data: CreateReligareProfileDto): Prisma.Prisma__ReligareProfileClient<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    updateProfile(id: string, data: UpdateReligareProfileDto): Prisma.Prisma__ReligareProfileClient<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    saveQuestionnaireResults(id: string, results: {
        answers: Prisma.InputJsonValue;
        kinNatal: number | null;
        kinData: Prisma.InputJsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.InputJsonValue;
        vocational: Prisma.InputJsonValue;
        synthesis: string;
        astrology: Prisma.InputJsonValue;
        dna: Prisma.InputJsonValue;
        humanDesign: Prisma.InputJsonValue;
        birthLat?: number | null;
        birthLng?: number | null;
        birthTz?: string | null;
    }): Prisma.Prisma__ReligareProfileClient<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    softDeleteProfile(id: string): Prisma.Prisma__ReligareProfileClient<{
        id: string;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    profileBelongsToOrg(orgId: string, id: string): Prisma.Prisma__ReligareProfileClient<{
        id: string;
    }, null, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
}
