import { Prisma, SubscriptionTier } from '@prisma/client';
import { ReligareRepository } from './religare.repository';
import { CreateReligareProfileDto, ReligareContext, SubmitQuestionnaireDto, UpdateReligareProfileDto } from '@gitroom/nestjs-libraries/dtos/religare/profile.dto';
export declare class ReligareService {
    private _religareRepository;
    constructor(_religareRepository: ReligareRepository);
    listProfiles(orgId: string, search?: string, page?: string): Promise<{
        items: {
            name: string;
            createdAt: Date;
            updatedAt: Date;
            id: string;
            status: string;
            expert: {
                name: string;
                id: string;
                handle: string;
                avatarUrl: string;
            };
            expertId: string;
            kinNatal: number;
            kinData: Prisma.JsonValue;
            archetypePrimary: string;
            archetypeSecondary: string;
        }[];
        total: number;
        page: number;
    }>;
    getProfile(orgId: string, id: string): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }>;
    getProfileByExpert(orgId: string, expertId: string): Prisma.Prisma__ReligareProfileClient<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }, null, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    createProfile(orgId: string, dto: CreateReligareProfileDto, tier?: SubscriptionTier | null): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }>;
    updateProfile(orgId: string, id: string, dto: UpdateReligareProfileDto): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }>;
    deleteProfile(orgId: string, id: string): Promise<{
        id: string;
    }>;
    submitQuestionnaire(orgId: string, id: string, dto: SubmitQuestionnaireDto): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }>;
    recompute(orgId: string, id: string): Promise<{
        name: string;
        createdAt: Date;
        updatedAt: Date;
        id: string;
        status: string;
        expert: {
            name: string;
            id: string;
            handle: string;
            avatarUrl: string;
        };
        dna: Prisma.JsonValue;
        expertId: string;
        birthDate: Date;
        birthTime: string;
        birthPlace: string;
        birthLat: number;
        birthLng: number;
        birthTz: string;
        answers: Prisma.JsonValue;
        kinNatal: number;
        kinData: Prisma.JsonValue;
        archetypePrimary: string;
        archetypeSecondary: string;
        archetypeScores: Prisma.JsonValue;
        vocational: Prisma.JsonValue;
        synthesis: string;
        astrology: Prisma.JsonValue;
        humanDesign: Prisma.JsonValue;
        brandProfile: Prisma.JsonValue;
        shareToken: string;
    }>;
    private _computeAndPersist;
    getContext(orgId: string): Promise<{
        context: ReligareContext;
    }>;
    setContext(orgId: string, context: ReligareContext): Promise<{
        context: "agency" | "therapy";
    }>;
    private _assertProfileExists;
}
