name: "Build MediaPublish Image"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Image
        run: |
          docker buildx build --platform linux/amd64 \
            -f Dockerfile.dev \
            -t ghcr.io/zgababa/media-publish:latest \
            -t ghcr.io/zgababa/media-publish:${{ github.sha }} \
            --provenance=false --sbom=false \
            --push .
