name: Make sure new PRs are sent to development

jobs:
  check-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # Do not checkout the repository here. See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for more information
      - uses: Vankka/pr-target-branch-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: dev # Don't prevent going from development -> main
          change-to: dev
          comment: |
              Your PR's base branch was set to `main`, PRs should be set to target `dev`.
              The base branch of this PR has been automatically changed to `development`, please check that there are no merge conflicts
