name: PR Quality

permissions:
  contents: read
  issues: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  anti-slop:
    runs-on: ubuntu-latest
    steps:
      - uses: peakoss/anti-slop@v0
        with:
          # Overall
          max-failures: 2
          require-maintainer-can-modify: true

          # Description
          max-emoji-count: 2
          max-code-references: 3

          # PR Template
          require-pr-template: true

          # User
          detect-spam-usernames: true
          min-account-age: 30
          max-daily-forks: 5
          min-profile-completeness: 4

          # Exemptions
          exempt-author-association: "OWNER,MEMBER,COLLABORATOR"
          exempt-users: "nevo-david,egelhaus"

          # Actions
          exempt-label: "exempt"
          close-pr: true
          failure-add-pr-labels: "spam"
