name: trufflehog
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
